#!/bin/bash
count=0
if [ "$1" = "--help" -o "$1" = "--h" -o "$1" = "-help" -o "$1" = "-h" -o "$1" = "" ]
then
echo -e "bash_backup: bash_backup filesDir backupDir extension [period] [maxBackupFiles] [backupStatus]"
echo -e " Makes a backup of all files from the specified folder"
echo -e ""
echo -e " Finds all files with specified extention in the folder and puts their archive copies in a special directory once in a while"
echo -e ""
echo -e " Arguments:"
echo -e " filesDir: Path to directory to backup."
echo -e " backupDir: Path to directory to store backups."
echo -e " extension: Extension of files to backup."
echo -e " period: Period of making backups in seconds. Default value is 60."
echo -e " maxBackupFiles: Number of backups that you need to store. Earlier versions will be replaced with more up-to-date versions in the course of work. Default value is 2."
echo -e " backupStatus: If backupStatus = 1 program will create LOGFILE.txt in folder ~/ where will be stored results of making backups. Backup ... was made successfully means that files integrity was not compromised. Error in ... means that an error occurred while creating a copy of the files. If backupStatus != 1 LOGFILE.txt will not be created. "
echo -e ""
echo -e " Exit status:"
echo -e " Program returns 0 if it was called with atribute --help. In other cases during normal operation it doesn't return anything and works in a constant loop."
exit 0;
fi
if [ -n "$4" ]
then
period=$4
else
period=60
fi
if [ -n "$5" ]
then
maxFilesNumber=$5
else
maxFilesNumber=2
fi
if [ -f LOGFILE.txt ]
then
rm -r ~/LOGFILE.txt
fi
if [ "$6" -eq 1 ]
then
touch ~/LOGFILE.txt
fi
cd $1
for((i=0;i>-1;i++))
do
let numb="$i%$maxFilesNumber+1"
filename="backup$numb.zip"

if [ -f $filename ]
then
rm -r $filename
fi
zip -r $filename $(find . -name "*$3") > /dev/null
if [ -f ~/UNZIPED ]
then
rm -r ~/UNZIPED
fi
mkdir ~/UNZIPED
unzip $filename -d ~/UNZIPED > /dev/null



cd ~/UNZIPED || exit
if [ -r forsum ]; then rm -r forsum; fi
mkdir forsum
cd forsum || exit
unzip -o $1$filename > /dev/null
for i in $(cat *$3 | md5sum) 
do
zipSum=$i
break
done
cd .. || exit
for i in $(cat *$3 | md5sum) 
do
origSum=$i
break
done
if [ "$origSum" = "$zipSum" ]; then echo "Backup Sueccessed"; else echo "Error"; fi
rm -r forsum
rm -r ~/UNZIPED
sleep $period
done
